apiVersion: v1
kind: Secret
metadata:
  name: summersafe-secrets
type: Opaque
# stringData allows passing plain text values instead of base64 encoding them (they are converted to base64 by Kubernetes)
stringData:
  MONGODB_URI: "mongodb+srv://admin:pass@cluster.mongodb.net/summersafe?retryWrites=true&w=majority"
  SESSION_SECRET: "your-super-strong-session-secret"
